language: node_js

node_js:
  - 'stable'

sudo: false

matrix:
  fast_finish: true

branches:
  only:
  - master

install:
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1

script:
 - npm test