language: node_js

node_js:
  - 'stable'
  - '8'
  - '6'

sudo: false

matrix:
  fast_finish: true

branches:
  only:
  - master
  - release-2.7
  - release-2.8

install:
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1

script:
 - npm test